# Site settings
title: "quanyechavshuo"
email: quanyechavshuo@gmail.com
description: "A blog about programming and network security"
baseurl: ""
url: https://3xp10it.cc
enforce_ssl: 3xp10it.cc
title_description: "<br><a href='mailto:quanyechavshuo@gmail.com'><font color='blue'>contact<font></a>"
title_image: "https://raw.githubusercontent.com/3xp10it/pic/master/1.png"
#google_analytics: "UA-20365477-4"
#
#disqus_account: quanyechavshuo
duoshuo_account: 3xp10it
github_repository: https://github.com/3xp10it/3xp10it.github.io
#addthis_id: ra-513c6fa83da6ec67
post_limit: 99999

# Social usernames/URLs
twitter_username: quanyechavshuo
github_username:  3xp10it

# Footer
# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

gems: [jekyll-paginate]

